name: Transient

on: [push, pull_request]

jobs:
  Test-Multi-Python:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
    - name: Install package dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ssh qemu libguestfs-tools
    - name: Setup tmate session
      uses: pdietl/action-tmate@v3
    - name: Run tests
      run: |
        make test-ci
